# Generated by Django 6.0.1 on 2026-01-26 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Imagen cuadrada de mínimo 400x400 px', null=True, upload_to='perfil/'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='imagen_producto',
            field=models.ImageField(blank=True, help_text='Imagen del producto en venta', null=True, upload_to='garage/'),
        ),
        migrations.CreateModel(
            name='ConfiguracionSecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_perfil', models.BooleanField(default=True, verbose_name='Mostrar Perfil Profesional')),
                ('mostrar_experiencia', models.BooleanField(default=True, verbose_name='Mostrar Experiencia Laboral')),
                ('mostrar_reconocimientos', models.BooleanField(default=True, verbose_name='Mostrar Reconocimientos')),
                ('mostrar_cursos', models.BooleanField(default=True, verbose_name='Mostrar Cursos Realizados')),
                ('mostrar_productos_academicos', models.BooleanField(default=True, verbose_name='Mostrar Productos Académicos')),
                ('mostrar_productos_laborales', models.BooleanField(default=True, verbose_name='Mostrar Productos Laborales')),
                ('mostrar_venta_garage', models.BooleanField(default=True, verbose_name='Mostrar Venta Garage')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.datospersonales')),
            ],
            options={
                'verbose_name': 'Configuración de Secciones',
                'verbose_name_plural': 'Configuraciones de Secciones',
            },
        ),
    ]
