# Generated by Django 6.0.1 on 2026-01-26 07:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_datospersonales_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen cuadrada de mínimo 400x400 px', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='imagen_producto',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del producto en venta', max_length=255, null=True, verbose_name='image'),
        ),
    ]
