# Generated by Django 6.0.1 on 2026-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, help_text='Certificado en PDF', null=True, upload_to='certificados/cursos/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, help_text='Certificado en PDF', null=True, upload_to='certificados/experiencia/'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, help_text='Certificado en PDF', null=True, upload_to='certificados/reconocimientos/'),
        ),
    ]
