# Generated by Django 6.0.1 on 2026-01-26 14:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Certificado en PDF', max_length=255, null=True, verbose_name='archivo'),
        ),
    ]
